image: bitnami/git:latest

stages:
  - test

tests:
  stage: test
  only:
    - branches
    - merge_requests
    - pushes

  except:
    - tags

  before_script:
    - 'sudo apt-get update'
    - 'sudo apt-get install -y shunit2'
    - 'git config --global user.email "${GITLAB_USER_EMAIL}"'
    - 'git config --global user.name "${GITLAB_USER_NAME}"'

  script:
    - "./tests.sh"
