stages:
  - test

tests:
  stage: test
  tags: ['dev']
  only:
    - branches
    - merge_requests
    - pushes

  except:
    - tags

  before_script:
    - 'git config --global user.email "runner@example.com"'
    - 'git config --global user.name "CI Runner"'

  script:
    - './tests.sh'

#test push 2
