name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: apt update
        run: sudo apt-get update

      - name: shunit install
        run: sudo apt-get install -y shunit2

      - name: set dummy credentials
        run: git config --global user.email "ci@example.com" && git config --global user.name "CI Action"

      - name: test
        run: ./tests.sh
