name: Version

on:
  workflow_run:
    workflows: ["Test"]
    types: ["completed"]
    branches: ["*"]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: debug echo 1
        run: echo git status

      - name: debug echo 2
        run: echo git branch
